[package]
name = "the_mop"
edition = "2024"

[environments]
testnet_utopia = "4c78adac"
testnet_stillness = "4c78adac"

[dependencies]
world = { git = "https://github.com/evefrontier/world-contracts.git", subdir = "contracts/world", rev = "main", override = true }

[dep-replacements.testnet_utopia]
world = { git = "https://github.com/evefrontier/world-contracts.git", subdir = "contracts/world", rev = "main", use-environment = "testnet_utopia" }

[dep-replacements.testnet_stillness]
world = { git = "https://github.com/evefrontier/world-contracts.git", subdir = "contracts/world", rev = "main", use-environment = "testnet_stillness" }
